import cv2
import numpy as np
import tensorflow as tf
import json
import os

IMG_SIZE = 224

model = tf.keras.models.load_model("paddy_disease_model.h5")

# Load class indices from training output (auto-generated by train_model.py)
# Falls back to alphabetical order if file doesn't exist
if os.path.exists("class_indices.json"):
    with open("class_indices.json", "r") as f:
        class_indices = json.load(f)
    # Invert: {index: name} and format names nicely
    class_labels = {
        v: k.replace("_", " ").title() for k, v in class_indices.items()
    }
    print(f"Loaded class labels from class_indices.json: {class_labels}")
else:
    # Fallback: alphabetical order matching flow_from_directory default
    class_labels = {
        0: "Bacterial Leaf Blight",
        1: "Brown Spot",
        2: "Healthy",
        3: "Leaf Smut"
    }
    print("Using default class labels (alphabetical)")


def predict_image(img_path):

    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # OpenCV loads BGR, model expects RGB
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.reshape(img, [1, IMG_SIZE, IMG_SIZE, 3])

    prediction = model.predict(img)

    class_index = int(np.argmax(prediction[0]))
    confidence = float(np.max(prediction[0])) * 100

    disease_name = class_labels.get(class_index, f"Unknown (index {class_index})")

    return disease_name, confidence